### ISSUE TITLE
new version?

### ISSUE THREAD

**Issue by apexad** [JosephDuffy/homebridge-pc-volume#532]
Looks like this homebridge plugin was last published to npmjs.com 5 months ago: https://www.npmjs.com/package/homebridge-pc-volume

With all the dependably merges for security issues of dependencies, do you think you can publish a new version?

**Comment by JosephDuffy** [comment]
There have been a lot of merges, but that's mainly because the dependabot settings are setup to create PRs quite aggressively.

Is there a particular merge you think is worthy of a release? The only security release I can see comes from a dev dependency so as a user it shouldn't be included as part of a homebridge install.

**Comment by apexad** [comment]
ok. guess it's fine then and may just be aggressively set dependabot as you mentioned.
