### ISSUE TITLE
Bug with dimmer slider

### ISSUE THREAD

**Issue by jeylites** [JosephDuffy/homebridge-pc-volume#709]
Thanks for developing this plugin it's very useful when it works. I'm not sure if I'm the only one having this issue, On the home app when I try to slide the volume to a specific level, it goes to zero. But when hit specific levels it stays at that level.

What does logarithmic do?

Here is my config
```
           "initiallyMuted": false,
            "switchVolumeDelta": 24,
            "switchDelay": 5,
            "logarithmic": false,
            "accessory": "ComputerSpeakers"
```

```
Node.js Version | v14.17.4
Npm Version  | v6.14.14
```

Hardware: MacMini Intel 2014

**Comment by jeylites** [comment]
If it's not too much to ask, It will be nice to be able to control Back, Next, Pause, Play

**Comment by JosephDuffy** [comment]
I've not had reports of this from anyone else but that doesn't mean there aren't others having the issue. I don't use this project any more myself since AirPlay 2 speakers have been available.

`logarithmic` will convert the 0-100 HomeKit values to 0-100 on a [logarithmic scale](https://techsupport.cambridgeaudio.com/hc/article_attachments/360000169198/log_lin_approx.jpg). This is done to better match our perception of volume. I think this is manly useful on Linux where the APIs are going to vary more.

One thing you could try is enabling debug logs in Homebridge to see which values Home is requesting and when. It sounds like it's requesting the volume while sliding and it's returning zero.

**Comment by JosephDuffy** [comment]
If you're able to provide logs I will look in to this, but unfortunately I don't have the time to debug without logs.
